seed: 3407
cuda: [0]
max_epochs: 100
batch_size: 8
num_workers: 8
lr: 0.0001

mode: train

dataset: YNLUAD
split: label/YNLUAD-split
label_file: label/YNLUAD_label.csv
data_dir: graphs/YNLUAD/edata-graph
text_file: graphs/YNLUAD/text_embedings.pkl

model_name: gps_net
loss: asl 
optimizer: adam
weight_decay: 0.0001

log_dir: logs
log_name: parameter
log_v: YNLUAD
load_best: true 
best_key: acc

# lr_scheduler: 
# lr_decay_steps: 20
# lr_decay_rate: 0.5
# lr_decay_min_lr: 0.0001
# CAM
heatmap: true
save_dir: heatmap

mean: [0.485, 0.456, 0.406]
std: [0.229, 0.224, 0.225]